"""agregar tablas servicios y proveedores

Revision ID: a523e2df2225
Revises: b2d4d5ab1188
Create Date: 2026-07-09 15:30:21.255301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a523e2df2225'
down_revision: Union[str, Sequence[str], None] = 'b2d4d5ab1188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadeo_crm_proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('max_beneficiarios', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_actividad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['mercadeo_crm_proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_titular_servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planliga_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['mercadeo_crm_servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercadeo_crm_titular_servicios')
    op.drop_table('mercadeo_crm_actividad')
    op.drop_table('mercadeo_crm_servicios')
    op.drop_table('mercadeo_crm_proveedores')
    # ### end Alembic commands ###
