"""agregar tablas crm comercial

Revision ID: b2d4d5ab1188
Revises: d9299531a017
Create Date: 2026-07-09 14:58:02.981301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d4d5ab1188'
down_revision: Union[str, Sequence[str], None] = 'd9299531a017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadeo_crm_embudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('industria', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('mercadeo_crm_contactos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_contacto', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('nombre1', sa.String(length=100), nullable=False),
    sa.Column('nombre2', sa.String(length=100), nullable=True),
    sa.Column('apellido1', sa.String(length=100), nullable=True),
    sa.Column('apellido2', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['mercadeo_crm_empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_etapas_embudo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('embudo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['embudo_id'], ['mercadeo_crm_embudos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_oportunidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('etapa_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('probabilidad', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('plan_liga_titular_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contacto_id'], ['mercadeo_crm_contactos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['mercadeo_crm_empresas.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['mercadeo_crm_etapas_embudo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_bitacora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('oportunidad_id', sa.Integer(), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('proximo_paso', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contacto_id'], ['mercadeo_crm_contactos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['mercadeo_crm_empresas.id'], ),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['mercadeo_crm_oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercadeo_crm_bitacora')
    op.drop_table('mercadeo_crm_oportunidades')
    op.drop_table('mercadeo_crm_etapas_embudo')
    op.drop_table('mercadeo_crm_contactos')
    op.drop_table('mercadeo_crm_empresas')
    op.drop_table('mercadeo_crm_embudos')
    # ### end Alembic commands ###
