"""agregar tabla importaciones

Revision ID: b69ada5831d9
Revises: a523e2df2225
Create Date: 2026-07-09 15:36:08.105772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69ada5831d9'
down_revision: Union[str, Sequence[str], None] = 'a523e2df2225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadeo_crm_importaciones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercadeo_crm_importaciones')
    # ### end Alembic commands ###
