"""crear tablas iniciales crm mercadeo marketing

Revision ID: d9299531a017
Revises: 
Create Date: 2026-07-09 13:44:17.229295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9299531a017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadeo_crm_campanas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_etiquetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_segmentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('filtros', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadeo_crm_campana_segmento',
    sa.Column('campana_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['mercadeo_crm_campanas.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['mercadeo_crm_segmentos.id'], ),
    sa.PrimaryKeyConstraint('campana_id', 'segmento_id')
    )
    op.create_table('mercadeo_crm_contacto_etiqueta',
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['mercadeo_crm_etiquetas.id'], ),
    sa.PrimaryKeyConstraint('contacto_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercadeo_crm_contacto_etiqueta')
    op.drop_table('mercadeo_crm_campana_segmento')
    op.drop_table('mercadeo_crm_segmentos')
    op.drop_table('mercadeo_crm_etiquetas')
    op.drop_table('mercadeo_crm_campanas')
    # ### end Alembic commands ###
